// <auto-generated />
using Avans.Demo.DataAccess.SqlLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avans.Demo.DataAccess.SqlLite.Migrations
{
    [DbContext(typeof(SqlLiteDataContext))]
    partial class SqlLiteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Avans.Demo.DataAccess.Entities.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Avans.Demo.DataAccess.Entities.Book", g =>
            {
                g.Property<string>("Title").HasColumnType("Text");
                g.Property<string>("ReleaseDate").HasColumnType("Text");
                g.Property<string>("Team").HasColumnType("Text");
                g.Property<double>("Rating").HasColumnType("REAL");
                g.Property<string>("Genre").HasColumnType("Text");

                g.HasKey("Title");

                g.ToTable("Games");
            });
#pragma warning restore 612, 618
        }
    }
}
