name: Docker Image CI

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

     
    - name: show content
      run: cat testfile.txt
      
    - name: Build the Docker image
      run: docker build . --file Avans.Demo/Avans.Demo.Web.Api/Dockerfile --tag my-image-name:$(date +%s)
