# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
    
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore Avans.Demo/Avans.Demo.Web.Api/Avans.Demo.Web.Api.csproj
    - name: Build
      run: dotnet build Avans.Demo/Avans.Demo.Web.Api/Avans.Demo.Web.Api.csproj --no-restore
    - name: Test
      run: dotnet test Avans.Demo/Avans.Demo.Web.Api/Avans.Demo.Web.Api.csproj --no-build --verbosity normal

    - name: Restore dependencies for test project
      run: dotnet restore Avans.Demo/Avans.Demo.Web.Api/Avans.Demo.Logic.Tests.csproj
    - name: Build test project
      run: dotnet build Avans.Demo/Avans.Demo.Web.Api/Avans.Demo.Logic.Tests.csproj --no-restore
    - name: Test test project
      run: dotnet test Avans.Demo/Avans.Demo.Web.Api/Avans.Demo.Logic.Tests.csproj --no-build --verbosity normal
